#!/bin/bash

set -eu
set -o pipefail

complement ()
{
  local A=`echo -e "$1" | sort -u`
  local B=`echo -e "$2" | sort -u`
  echo -e "$A\n$B\n$B" | sort | uniq -u
}

REMOTE_BRANCHES=$(git ls-remote -h ${GIT_REPO} | sed 's_.*refs/heads/__g' | sed 's/[^a-zA-Z0-9_]/-/g' | sort -u)
LOCAL_BRANCHES=$(kubectl --namespace=${NAMESPACE} get ${RESOURCES} -a -o json | jq -r '.items | map(select(.metadata.labels.branch != null) | .metadata.labels.branch) | .[]' | sort -u)
DELETE_BRANCHES=$(complement "${LOCAL_BRANCHES}" "${REMOTE_BRANCHES}")

for BRANCH in ${DELETE_BRANCHES}; do
  kubectl --namespace=${NAMESPACE} delete ${RESOURCES} -l branch=${BRANCH}
done
